[project]
name = "lpt-stake"
version = "0.1.0"
description = "Libraries for Livepeer emissions risk analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2",
    "polars>=1.26.0",
]

[project.optional-dependencies]
fetch = [
    "requests>=2.32.5",
    "web3>=7.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "marimo[lsp]>=0.17.7",
    "pytest>=9.0.2",
]
notebook = [
    "altair>=6",
    "marimo>=0.17.7",
    "matplotlib>=3.10.1",
]
